# Generated by Django 4.2.8 on 2023-12-22 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_productimage_image_productimage_image_url_and_more'),
        ('order', '0009_alter_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderlines', to='product.product'),
        ),
    ]
